{{- $name := include "kanboard.name" . -}}

{{- if .Values.route.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.route.labels }}
    {{- toYaml .Values.route.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.route.annotations }}
  annotations:
    {{- toYaml .Values.route.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.route.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $name }}
          port: {{ .Values.clusterip.port }}
{{- end }}
